Misc improvements
ldab/KXTJ3-1057 pull request #2
Opened 2021-08-24 16:14 UTC by cammiboi

- Fix intConf function to correctly set the int pin to non-latching mode
- Fix intConf function to set int pin polarity active high when polarity = HIGH
- Add function isMotionInt which returns true when interrupt is triggered, and 0 if no activity timer expires

2023-05-29 05:11 UTC, ldab requested changes

2023-05-29 05:11 UTC, ldab commented on src/kxtj3-1057.cpp
> +	uint8_t dataToWrite = 0x2A;  		// Interrupt enabled, active LOW, non-latched
This in combination with ULMOD will set to pulsed.

2023-06-20 19:15 UTC, nomakewan commented
Going to recommend closing this PR without merging as it is made obsolete by the latest version of the library.

2024-06-05 20:45 UTC, ldab commented
Closing due to no activity.

2024-06-05 20:45 UTC, closed without merging